web/cts/grails-app/domain/edu/ucdavis/fiehnlab/cts/Compound.groovy
package edu.ucdavis.fiehnlab.cts

import grails.converters.JSON

class Compound {
	String inchiKey
	String inchiCode
	Double molWeight = 0d
	Double exactMass = 0d
	String formula
	String sourceFile
	Integer dataSourcesCount = 0
	Integer referencesCount = 0
	Integer pubmedHits = 0

	static hasMany = [synonyms: Synonym, extIds: ExternalId]

	static mapping = {
		version false
		id generator: 'assigned', name: 'inchiKey'
		inchiKey unique:true, column: 'id'
		inchiCode type: 'text'
		formula type: 'text'
		exactMass precision: 5, scale: 5
		molWeight precision: 5, scale: 5
        synonyms lazy: false
        extIds lazy: false
		dataSourcesCount defaultValue: "0"
		referencesCount defaultValue: "0"
		pubmedHits defaultValue: "0"
	}

	static constraints = {
		inchiKey nullable: false, blank: false, size: 27..27
		inchiCode nullable: true, type: 'text'
		formula nullable: true, type: 'text'
		exactMass min: 0d, scale: 5, default: 0d
		molWeight min: 0d, scale: 5, default: 0d
	}

	def toJson() {
		def result = [:]
		result.inchikey = this.inchiKey
		result.inchicode = this.inchiCode
		result.molweight = this.molWeight <= 0.0 ? null : this.molWeight
		result.exactmass = this.exactMass <= 0.0 ? null : this.exactMass
		result.formula = this.formula

		result.synonyms = this.synonyms.collect{syn -> [type:syn.type,name:syn.name,score:0]}
		result.externalIds = this.extIds.collect{id -> [name:id.name,value:id.value,url:id.url]}

		result.dataSourcesCount = this.dataSourcesCount
		result.referencesCount = this.referencesCount
		result.pubmedHits = this.pubmedHits

		return result as JSON
	}


	String getId() {
		inchiKey
	}

	void setId(String inchiKey) {
		id = inchiKey
	}

	String toString() {
		inchiKey
	}

	int hashCode() {
		toString().hashCode()
	}

	boolean equals(Object obj) {
		if (!obj) { return false }

		if(obj instanceof Compound){

			Compound comp = (Compound) obj
			if (!this.inchiKey.equals(comp.inchiKey)) { return false }
			if (!this.inchiCode.equals(comp.inchiCode)) { return false }

			return true
		} else {
			return false
		}
	}
}

web/cts/grails-app/controllers/edu/ucdavis/fiehnlab/cts/CompoundController.groovy
package edu.ucdavis.fiehnlab.cts

import grails.converters.JSON
import org.springframework.dao.DataIntegrityViolationException

class CompoundController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def show(String id) {
        def compoundInstance = Compound.get(id)
        if (!compoundInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'compound.label', default: 'Compound'), id])
            redirect controller: "index"
            return
        }

        [compoundInstance: compoundInstance]
    }

    /**
     * returns the IUPac Names for a compound
     * @param id
     */
    def ajaxGetIUPacNameForCompound(String id){
        render template: "renderIUPACNames", model: [synonyms:Synonym.findAllByInchiKeyAndTypeLike(Compound.get(id),"IUPAC Name%").sort {a,b -> a.type.compareToIgnoreCase b.type}]
    }

    /**
     * returns
     * @param id
     */
    def ajaxGetSynonymsForCompound(String id){
        render template: "renderSynonyms", model: [synonyms:Synonym.findAllByInchiKeyAndTypeNotLike(Compound.get(id),"IUPAC Name%").sort {a,b -> a.type.compareToIgnoreCase b.type}]
    }

}

web/cts/grails-app/views/compound/_compoundTemplate.gsp
<div class='compound'>
<g:each in='${ compound?.synonyms }' var='syn'>
<g:if test='${"IUPAC Name (Preferred)".equals(syn.type)}'>
	<p><span class='compound.label'>Compound:</span> <span class='compound.value'>${syn.name}</span></p>
</g:if>
</g:each>
	<p class='compound.details'>
		<span class='compound.label'>InChI Key:</span> <span class='compound.value'>${compound?.inchiKey}<br/></span>
		<span class='compound.label'>InChI Code:</span> <span class='compound.value'>${compound?.inchiCode ?: "Not Found"}<br/></span>
		<span class='compound.label'>Molecular weight:</span> <span class='compound.value'>${compound?.molWeight}</span>
	</p>
	<div class="hr"></div>
	<g:each in="${compound?.extIds}" var="extid">
		<p>${extid?.name}: ${extid?.value}</p>
	</g:each>
	<g:each in="${compound?.synonyms}" var="syn">
		<p>${syn?.type}: ${syn?.name}</p>
	</g:each>
	<div class="hr"></div>

</div>

web/cts/grails-app/views/compound/_form.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Compound" %>



<div class="fieldcontain ${hasErrors(bean: compoundInstance, field: 'inchiCode', 'error')} ">
	<label for="inchiCode">
		<g:message code="compound.inchiCode.label" default="Inchi Code" />
		
	</label>
	<g:textField name="inchiCode" value="${compoundInstance?.inchiCode}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: compoundInstance, field: 'molWeight', 'error')} required">
	<label for="molWeight">
		<g:message code="compound.molWeight.label" default="Mol Weight" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="molWeight" value="${fieldValue(bean: compoundInstance, field: 'molWeight')}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: compoundInstance, field: 'extIds', 'error')} ">
	<label for="extIds">
		<g:message code="compound.extIds.label" default="Ext Ids" />
		
	</label>
	<g:select name="extIds" from="${edu.ucdavis.fiehnlab.cts.ExternalId.list()}" multiple="multiple" optionKey="id" size="5" value="${compoundInstance?.extIds*.id}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: compoundInstance, field: 'inchiKey', 'error')} ">
	<label for="inchiKey">
		<g:message code="compound.inchiKey.label" default="Inchi Key" />
		
	</label>
	<g:textField name="inchiKey" value="${compoundInstance?.inchiKey}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: compoundInstance, field: 'synonyms', 'error')} ">
	<label for="synonyms">
		<g:message code="compound.synonyms.label" default="Synonyms" />
		
	</label>
	<g:select name="synonyms" from="${edu.ucdavis.fiehnlab.cts.Synonym.list()}" multiple="multiple" optionKey="id" size="5" value="${compoundInstance?.synonyms*.id}" class="many-to-many"/>
</div>

web/cts/grails-app/views/compound/_renderIUPACNames.gsp
<table>
    <thead>
        <tr>
            <th>Type</th>
            <th>Name</th>

        </tr>
    </thead>
    <tbody>
    <g:each var="syn" in="${synonyms}">

        <tr>
            <td>${syn.type}</td>
            <td>${syn.name}</td>

        </tr>
    </g:each>

    </tbody>
</table>

web/cts/grails-app/views/compound/_renderSynonyms.gsp
<!-- display our list in several columns to make it look nice and not take up so much space -->
<ul class="multi-column">
    <g:each in="${synonyms}" var="synonym" status="i">
        <li>${synonym.name}</li>
    </g:each>
</ul>
<br class="multi-column clear"/>

web/cts/grails-app/views/compound/create.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Compound" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'compound.label', default: 'Compound')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-compound" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-compound" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${compoundInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${compoundInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/compound/edit.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Compound" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'compound.label', default: 'Compound')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-compound" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-compound" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${compoundInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${compoundInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${compoundInstance?.id}" />
				<g:hiddenField name="version" value="${compoundInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/compound/list.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Compound" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'compound.label', default: 'Compound')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-compound" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-compound" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="inchiKey" title="${message(code: 'compound.inchiKey.label', default: 'Inchi Key')}" />
					
						<g:sortableColumn property="inchiCode" title="${message(code: 'compound.inchiCode.label', default: 'Inchi Code')}" />
					
						<g:sortableColumn property="molWeight" title="${message(code: 'compound.molWeight.label', default: 'Molecular Weight')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${compoundInstanceList}" status="i" var="compoundInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${compoundInstance.inchiKey}">${fieldValue(bean: compoundInstance, field: "inchiKey")}</g:link></td>
					
						<td>${fieldValue(bean: compoundInstance, field: "inchiCode")}</td>
					
						<td>${fieldValue(bean: compoundInstance, field: "molWeight")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${compoundInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

web/cts/grails-app/views/compound/show.gsp
<!doctype html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'compound.label', default: 'Compound')}"/>
	<title>Compound Details</title>
</head>

<body>

<div class="page_header">
	<h2>Compound Details</h2>

	<p class="siteinfo">
		Welcome, here you can see all information we have about the currently selected compound.
	</p>

	<div class="hr"></div>

	<div class="box">

		<div>
			<ul class="results">
				<li>
					<div class="left">
						<h3>General Information</h3>

						<ul>
							<li>Associated names: ${compoundInstance.synonyms.size()}</li>
							<li>Molecular weight: ${compoundInstance.molWeight}</li>
							<li>Exact mass: ${compoundInstance.exactMass}</li>
							<li>Formula: ${compoundInstance.formula}</li>
							<li>Known Id's: ${compoundInstance.extIds.size()}</li>
							<li>InChI code: ${compoundInstance.inchiCode}</li>
							<li>InChI key: ${compoundInstance.inchiKey}</li>
						</ul>

					</div>

					<div class="right">
						<h3>Structure Information</h3>

						%{--<g:structureMedium3D id="${compoundInstance.id}" inchi="${compoundInstance.inchiCode}"/>--}%
						<g:structureMedium id="${compoundInstance.id}" inchi="${compoundInstance.inchiCode}"/>
					</div>

					<div class="clear"></div>
				</li>
			</ul>
			<ul class="treeList">
				<h3>External Id Information</h3>

				<cts:extIdTree data="${compoundInstance.extIds}"/>
			</ul>
			<ul class="results">
				<li>
					<h3>IUPac Names</h3>

					<div id="iupac"><div class="spinner"></div></div>
					<jq:jquery>
						<g:remoteFunction controller="compound" action="ajaxGetIUPacNameForCompound"
						                  id="${compoundInstance.inchiKey}" update="iupac"/>
					</jq:jquery>
				</li>
				<li>
					<h3>Synonyms</h3>

					<div id="synonyms"><div class="spinner"></div></div>

					<jq:jquery>
						<g:remoteFunction controller="compound" action="ajaxGetSynonymsForCompound"
						                  id="${compoundInstance.inchiKey}" update="synonyms"/>
					</jq:jquery>
				</li>
			</ul>
		</div>
	</div>
</div>

</body>
</html>