web/cts/grails-app/domain/edu/ucdavis/fiehnlab/cts/ExternalId.groovy
package edu.ucdavis.fiehnlab.cts

/**
 * what does this represent?
 * @author dpedrosa
 *
 */
class ExternalId {
//	long id
//	String inchiKey
	String name
	String url
	String value
	
	static belongsTo = [inchiKey: Compound]
	
	static optionals = ['url']
		
    static constraints = {
		inchiKey nullable: false, unique:['name','value']
		name nullable: false, blank: false	// who created the id: PubChem, HMDB, CAS... etc
		url url: true
		value nullable: false, blank: false // actual value for the id
    }

	static mapping = {
		inchiKey column: 'inchi_key'
		name type: 'text'
		value type: 'text'
		version false
	}
	
	String toString() { "${name}:${value} (${url})" }
	
	int hashCode() { return toString().hashCode() }
	
	boolean equals(Object obj) {
		if (!obj) { return false }
		
		if (obj instanceof ExternalId) {
			
			ExternalId extid = (ExternalId) obj
			if (!this.name.equals(extid.name)) { return false }
			if (!this.url.equals(extid.url)) { return false }
			if (!this.value.equals(extid.value)) { return false }
			
			return true
		} else {
			return false
		}
	}
}

web/cts/grails-app/controllers/edu/ucdavis/fiehnlab/cts/ExternalIdController.groovy
package edu.ucdavis.fiehnlab.cts

class ExternalIdController {

	/*
	 * default asction to redirect to index page, since there's nothing to see here
	 */
	def index() {
		redirect controller: "index"
		return
	}
}

web/cts/grails-app/views/externalId/_form.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.ExternalId" %>



<div class="fieldcontain ${hasErrors(bean: externalIdInstance, field: 'origin', 'error')} ">
	<label for="origin">
		<g:message code="externalId.origin.label" default="Origin" />
		
	</label>
	<g:textField name="origin" value="${externalIdInstance?.origin}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: externalIdInstance, field: 'value', 'error')} ">
	<label for="value">
		<g:message code="externalId.value.label" default="Value" />
		
	</label>
	<g:textField name="value" value="${externalIdInstance?.value}"/>
</div>

web/cts/grails-app/views/externalId/create.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.ExternalId" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'externalId.label', default: 'ExternalId')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-externalId" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-externalId" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${externalIdInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${externalIdInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/externalId/edit.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.ExternalId" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'externalId.label', default: 'ExternalId')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-externalId" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-externalId" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${externalIdInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${externalIdInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${externalIdInstance?.id}" />
				<g:hiddenField name="version" value="${externalIdInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/externalId/list.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.ExternalId" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'externalId.label', default: 'ExternalId')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-externalId" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-externalId" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="origin" title="${message(code: 'externalId.origin.label', default: 'Origin')}" />
					
						<g:sortableColumn property="value" title="${message(code: 'externalId.value.label', default: 'Value')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${externalIdInstanceList}" status="i" var="externalIdInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${externalIdInstance.id}">${fieldValue(bean: externalIdInstance, field: "origin")}</g:link></td>
					
						<td>${fieldValue(bean: externalIdInstance, field: "value")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${externalIdInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

web/cts/grails-app/views/externalId/show.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.ExternalId" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'externalId.label', default: 'ExternalId')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-externalId" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-externalId" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list externalId">
			
				<g:if test="${externalIdInstance?.origin}">
				<li class="fieldcontain">
					<span id="origin-label" class="property-label"><g:message code="externalId.origin.label" default="Origin" /></span>
					
						<span class="property-value" aria-labelledby="origin-label"><g:fieldValue bean="${externalIdInstance}" field="origin"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${externalIdInstance?.value}">
				<li class="fieldcontain">
					<span id="value-label" class="property-label"><g:message code="externalId.value.label" default="Value" /></span>
					
						<span class="property-value" aria-labelledby="value-label"><g:fieldValue bean="${externalIdInstance}" field="value"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${externalIdInstance?.id}" />
					<g:link class="edit" action="edit" id="${externalIdInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>