web/cts/grails-app/domain/edu/ucdavis/fiehnlab/cts/Synonym.groovy
package edu.ucdavis.fiehnlab.cts

/**
 * what does this represent
 * @author dpedrosa
 *
 */
class Synonym {
//	long id
//	String inchiKey
	String type
	String name
	Double score

	static belongsTo = [inchiKey: Compound]
	
	static constraints = {
		inchiKey nullable: false, unique:['type','name']
		type inList: ['IUPAC Name (Traditional)',
			'IUPAC Name (Systematic)',
			'IUPAC Name (CAS-like Style)',
			'IUPAC Name (Allowed)',
			'IUPAC Name (Preferred)',
			'Synonym']
		name nullable: false, blank: false
		score nullable: false, default: 0d
	}

	static mapping = {
		inchiKey column: 'inchi_key'
		name type: 'text'
		version false
	}

	@Override
	String toString() { "${type}: ${name}" }

	@Override
	int hashCode() { return toString().hashCode() }

	@Override
	boolean equals(Object obj) {
		if (!obj) { return false }

		if (obj instanceof Synonym) {

			Synonym syn = (Synonym) obj
			if (!this.name.equals(syn.name)) { return false }
			if (!this.type.equals(syn.type)) { return false }
			if (!this.score.equals(syn.score)) { return false }
	
			return true
		} else {
			return false
		}
	}
}

web/cts/grails-app/controllers/edu/ucdavis/fiehnlab/cts/SynonymController.groovy
package edu.ucdavis.fiehnlab.cts

class SynonymController {

	/*
	 * default asction to redirect to index page, since there's nothing to see here
	 */
	def index() {
		redirect controller: "index"
		return
	}
}

web/cts/grails-app/views/synonym/_form.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Synonym" %>



<div class="fieldcontain ${hasErrors(bean: synonymInstance, field: 'type', 'error')} ">
	<label for="type">
		<g:message code="synonym.type.label" default="Type" />
		
	</label>
	<g:textField name="type" value="${synonymInstance?.type}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: synonymInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="synonym.name.label" default="Name" />
		
	</label>
	<g:textField name="name" value="${synonymInstance?.name}"/>
</div>

web/cts/grails-app/views/synonym/create.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Synonym" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'synonym.label', default: 'Synonym')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-synonym" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-synonym" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${synonymInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${synonymInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/synonym/edit.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Synonym" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'synonym.label', default: 'Synonym')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-synonym" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-synonym" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${synonymInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${synonymInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${synonymInstance?.id}" />
				<g:hiddenField name="version" value="${synonymInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

web/cts/grails-app/views/synonym/list.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Synonym" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'synonym.label', default: 'Synonym')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-synonym" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-synonym" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="type" title="${message(code: 'synonym.type.label', default: 'Type')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'synonym.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${synonymInstanceList}" status="i" var="synonymInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${synonymInstance.id}">${fieldValue(bean: synonymInstance, field: "type")}</g:link></td>
					
						<td>${fieldValue(bean: synonymInstance, field: "name")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${synonymInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

web/cts/grails-app/views/synonym/show.gsp
<%@ page import="edu.ucdavis.fiehnlab.cts.Synonym" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'synonym.label', default: 'Synonym')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-synonym" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-synonym" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list synonym">
			
				<g:if test="${synonymInstance?.type}">
				<li class="fieldcontain">
					<span id="type-label" class="property-label"><g:message code="synonym.type.label" default="Type" /></span>
					
						<span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${synonymInstance}" field="type"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${synonymInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="synonym.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${synonymInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${synonymInstance?.id}" />
					<g:link class="edit" action="edit" id="${synonymInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>